import type { PoolClient } from "pg";
import { pool } from "@/db";
import { hashIp } from "@/lib/security";

export const ORDER_STATUSES=["pending","confirmed","processing","preparing","shipped","delivered","cancelled","returned","refunded"] as const;
export type OrderStatus=(typeof ORDER_STATUSES)[number];
export const PAYMENT_STATUSES=["unpaid","pending","paid","failed","refunded","partially_refunded"] as const;
export type PaymentStatus=(typeof PAYMENT_STATUSES)[number];
const ORDER_TRANSITIONS:Record<OrderStatus,readonly OrderStatus[]>={pending:["cancelled"],confirmed:["processing","cancelled"],processing:["preparing","cancelled"],preparing:["shipped","cancelled"],shipped:["delivered","returned"],delivered:["returned"],returned:[],cancelled:[],refunded:[]};
const PAYMENT_TRANSITIONS:Record<PaymentStatus,readonly PaymentStatus[]>={unpaid:["pending","failed"],pending:["failed"],failed:["pending"],paid:[],partially_refunded:[],refunded:[]};
const SHIPPING_TRANSITIONS:Record<string,readonly string[]>={pending:["preparing"],preparing:["shipped"],shipped:["delivered","returned"],delivered:["returned"],returned:[]};
export class StateConflictError extends Error{constructor(message:string,public code="state_conflict"){super(message)}}
export const canAdminTransitionOrder=(from:string,to:string)=>from===to||Boolean(ORDER_TRANSITIONS[from as OrderStatus]?.includes(to as OrderStatus));
export const canAdminTransitionPayment=(from:string,to:string)=>from===to||Boolean(PAYMENT_TRANSITIONS[from as PaymentStatus]?.includes(to as PaymentStatus));
export const canAdminTransitionShipping=(from:string,to:string)=>from===to||Boolean(SHIPPING_TRANSITIONS[from]?.includes(to));

async function auditTx(c:PoolClient,x:{adminId?:number|null;action:string;targetType:string;targetId?:string|number|null;metadata?:Record<string,unknown>;ip?:string}){await c.query("INSERT INTO admin_activity_logs(admin_id,action,target_type,target_id,metadata,ip_hash) VALUES($1,$2,$3,$4,$5::jsonb,$6)",[x.adminId??null,x.action,x.targetType,x.targetId==null?null:String(x.targetId),JSON.stringify(x.metadata??{}),x.ip?hashIp(x.ip):null])}

async function restoreInventoryOnce(c:PoolClient,order:{id:number;publicId:string},adminId:number){
 const sales=await c.query<{id:number;product_id:number;quantity:number}>("SELECT id,product_id,quantity FROM inventory_transactions WHERE reference_type='order' AND reference_id=$1 AND type='sale' ORDER BY product_id,id FOR UPDATE",[String(order.id)]);
 for(const sale of sales.rows){const key=`cancel:${order.id}:sale:${sale.id}`;if((await c.query("SELECT 1 FROM inventory_transactions WHERE idempotency_key=$1",[key])).rowCount)continue;const p=await c.query<{stock:number}>("SELECT stock FROM products WHERE id=$1 FOR UPDATE",[sale.product_id]);if(!p.rowCount)throw new StateConflictError("محصول سفارش دیگر موجود نیست");const before=Number(p.rows[0].stock),qty=Math.abs(Number(sale.quantity)),after=before+qty;await c.query("UPDATE products SET stock=$1,updated_at=NOW() WHERE id=$2",[after,sale.product_id]);await c.query("INSERT INTO inventory_transactions(product_id,type,quantity,stock_before,stock_after,reason,reference_type,reference_id,idempotency_key,admin_id) VALUES($1,'return',$2,$3,$4,$5,'order',$6,$7,$8)",[sale.product_id,qty,before,after,`لغو سفارش ${order.publicId}`,String(order.id),key,adminId])}
}

type LockedPayment={payment_id:number;payment_status:string;provider:string;demo_token_used_at:Date|null;ref_id:string|null;order_id:number;order_status:string;public_id:string;customer_name:string;total_toman:number};
async function lockPayment(c:PoolClient,authority:string){const r=await c.query<LockedPayment>(`SELECT p.id payment_id,p.status payment_status,p.provider,p.demo_token_used_at,p.ref_id,o.id order_id,o.status order_status,o.public_id,o.customer_name,o.total_toman FROM payments p JOIN orders o ON o.id=p.order_id WHERE p.authority=$1 FOR UPDATE OF p,o`,[authority]);return r.rows[0]}

export async function finalizePayment(input:{authority:string;refId:string;cardPan:string|null;expectedProvider:"demo"|"zarinpal";consumeDemoToken?:boolean}){
 const c=await pool.connect();try{await c.query("BEGIN");const row=await lockPayment(c,input.authority);if(!row||row.provider!==input.expectedProvider)throw new StateConflictError("تراکنش پیدا نشد","not_found");if(input.consumeDemoToken&&row.demo_token_used_at)throw new StateConflictError("توکن درگاه قبلاً استفاده شده است","token_replayed");if(row.payment_status==="verified"){await c.query("COMMIT");return{alreadyProcessed:true,publicId:row.public_id,total:Number(row.total_toman),refId:row.ref_id??input.refId}}if(row.payment_status!=="pending"||row.order_status!=="pending")throw new StateConflictError("وضعیت تراکنش اجازه تأیید پرداخت را نمی‌دهد");
 const items=await c.query<{product_id:number|null;qty:number;name:string}>("SELECT product_id,SUM(qty)::int qty,MIN(name) name FROM order_items WHERE order_id=$1 GROUP BY product_id ORDER BY product_id NULLS LAST",[row.order_id]);if(!items.rowCount)throw new StateConflictError("سفارش بدون کالا قابل پرداخت نیست");
 for(const item of items.rows){if(item.product_id==null)throw new StateConflictError(`محصول «${item.name}» دیگر قابل فروش نیست`);const u=await c.query<{id:number;stock:number;min_stock:number;name:string}>("UPDATE products SET stock=stock-$1,updated_at=NOW() WHERE id=$2 AND deleted_at IS NULL AND stock >= $1 RETURNING id,stock,min_stock,name",[item.qty,item.product_id]);if(!u.rowCount)throw new StateConflictError(`موجودی «${item.name}» کافی نیست`,"insufficient_stock");const p=u.rows[0],key=`payment:${row.payment_id}:product:${item.product_id}`;await c.query("INSERT INTO inventory_transactions(product_id,type,quantity,stock_before,stock_after,reason,reference_type,reference_id,idempotency_key) VALUES($1,'sale',$2,$3,$4,$5,'order',$6,$7)",[item.product_id,-item.qty,Number(p.stock)+item.qty,Number(p.stock),`فروش سفارش ${row.public_id}`,String(row.order_id),key]);if(Number(p.stock)<=Number(p.min_stock))await c.query("INSERT INTO notifications(type,title,body,target_url) VALUES($1,$2,$3,$4)",[Number(p.stock)===0?"out_of_stock":"low_stock",Number(p.stock)===0?"اتمام موجودی":"کاهش موجودی",`${p.name} به ${p.stock} عدد رسید.`,`/admin/products/${p.id}`])}
 await c.query("UPDATE payments SET status='verified',ref_id=$1,card_pan=$2,verified_at=NOW(),demo_token_used_at=CASE WHEN $3 THEN NOW() ELSE demo_token_used_at END WHERE id=$4",[input.refId,input.cardPan,Boolean(input.consumeDemoToken),row.payment_id]);await c.query("UPDATE orders SET status='confirmed',payment_status='paid',paid_at=NOW(),updated_at=NOW() WHERE id=$1",[row.order_id]);await c.query("INSERT INTO order_events(order_id,type,from_value,to_value,note,idempotency_key) VALUES($1,'payment_verified',$2,'paid',$3,$4)",[row.order_id,row.payment_status,input.refId,`payment:${row.payment_id}:verified`]);await c.query("INSERT INTO notifications(type,title,body,target_url) VALUES('new_order',$1,$2,$3)",[`سفارش جدید ${row.public_id}`,`${row.customer_name} — ${Number(row.total_toman).toLocaleString("fa-IR")} تومان`,`/admin/orders/${row.public_id}`]);await auditTx(c,{action:"payment.verified",targetType:"order",targetId:row.public_id,metadata:{paymentId:row.payment_id,provider:row.provider}});await c.query("COMMIT");return{alreadyProcessed:false,publicId:row.public_id,total:Number(row.total_toman),refId:input.refId}
 }catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}
}

export async function cancelDemoPayment(authority:string){const c=await pool.connect();try{await c.query("BEGIN");const r=await lockPayment(c,authority);if(!r||r.provider!=="demo")throw new StateConflictError("تراکنش پیدا نشد","not_found");if(r.demo_token_used_at)throw new StateConflictError("توکن درگاه قبلاً استفاده شده است","token_replayed");if(r.payment_status!=="pending"||r.order_status!=="pending")throw new StateConflictError("این تراکنش دیگر قابل لغو نیست");await c.query("UPDATE payments SET status='cancelled',demo_token_used_at=NOW() WHERE id=$1",[r.payment_id]);await c.query("UPDATE orders SET status='cancelled',payment_status='failed',updated_at=NOW() WHERE id=$1",[r.order_id]);await c.query("INSERT INTO order_events(order_id,type,from_value,to_value,idempotency_key) VALUES($1,'status','pending','cancelled',$2)",[r.order_id,`demo:${r.payment_id}:cancelled`]);await auditTx(c,{action:"payment.cancelled",targetType:"order",targetId:r.public_id,metadata:{paymentId:r.payment_id,provider:"demo"}});await c.query("COMMIT");return{publicId:r.public_id}}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}

export async function cancelPendingGatewayPayment(authority:string){const c=await pool.connect();try{await c.query("BEGIN");const r=await lockPayment(c,authority);if(!r||r.provider!=="zarinpal")throw new StateConflictError("تراکنش پیدا نشد","not_found");if(r.payment_status==="cancelled"&&r.order_status==="cancelled"){await c.query("COMMIT");return{publicId:r.public_id,alreadyProcessed:true}}if(r.payment_status!=="pending"||r.order_status!=="pending")throw new StateConflictError("این تراکنش دیگر قابل لغو نیست");await c.query("UPDATE payments SET status='cancelled' WHERE id=$1",[r.payment_id]);await c.query("UPDATE orders SET status='cancelled',payment_status='failed',updated_at=NOW() WHERE id=$1",[r.order_id]);await c.query("INSERT INTO order_events(order_id,type,from_value,to_value,idempotency_key) VALUES($1,'status','pending','cancelled',$2)",[r.order_id,`gateway:${r.payment_id}:cancelled`]);await auditTx(c,{action:"payment.cancelled",targetType:"order",targetId:r.public_id,metadata:{paymentId:r.payment_id,provider:"zarinpal"}});await c.query("COMMIT");return{publicId:r.public_id,alreadyProcessed:false}}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}

export async function updateOrderByAdmin(input:{publicId:string;adminId:number;status?:OrderStatus;paymentStatus?:PaymentStatus;shippingStatus?:string;internalNote?:string;ip?:string}){const c=await pool.connect();try{await c.query("BEGIN");const q=await c.query("SELECT * FROM orders WHERE public_id=$1 FOR UPDATE",[input.publicId]);if(!q.rowCount)throw new StateConflictError("سفارش پیدا نشد","not_found");const o=q.rows[0],status=input.status??o.status;let payment=input.paymentStatus??o.payment_status;const shipping=input.shippingStatus??o.shipping_status,note=input.internalNote??o.internal_note;if(status==="cancelled"&&["paid","partially_refunded"].includes(o.payment_status))throw new StateConflictError("لغو سفارش پرداخت‌شده تا زمان اجرای فرایند بازپرداخت مجاز نیست","refund_required");if(status==="cancelled"&&["unpaid","pending"].includes(o.payment_status))payment="failed";if(!canAdminTransitionOrder(o.status,status))throw new StateConflictError(`تغییر وضعیت ${o.status} به ${status} مجاز نیست`);if(!canAdminTransitionPayment(o.payment_status,payment))throw new StateConflictError("وضعیت پرداخت فقط از مسیر پرداخت یا بازپرداخت قابل تغییر است");if(!canAdminTransitionShipping(o.shipping_status,shipping))throw new StateConflictError(`تغییر وضعیت ارسال ${o.shipping_status} به ${shipping} مجاز نیست`);if(status==="cancelled"&&o.status!=="cancelled"){await c.query("UPDATE payments SET status='cancelled' WHERE order_id=$1 AND status='pending'",[o.id]);await restoreInventoryOnce(c,{id:o.id,publicId:o.public_id},input.adminId);}await c.query("UPDATE orders SET status=$1,payment_status=$2,shipping_status=$3,internal_note=$4,updated_at=NOW() WHERE id=$5",[status,payment,shipping,note,o.id]);for(const[type,from,to]of[["status",o.status,status],["payment_status",o.payment_status,payment],["shipping_status",o.shipping_status,shipping]] as const)if(from!==to)await c.query("INSERT INTO order_events(order_id,admin_id,type,from_value,to_value) VALUES($1,$2,$3,$4,$5)",[o.id,input.adminId,type,from,to]);if(input.internalNote!==undefined&&input.internalNote!==o.internal_note)await c.query("INSERT INTO order_events(order_id,admin_id,type,note) VALUES($1,$2,'note',$3)",[o.id,input.adminId,input.internalNote]);await auditTx(c,{adminId:input.adminId,action:"order.updated",targetType:"order",targetId:input.publicId,metadata:{from:o.status,to:status,paymentFrom:o.payment_status,paymentTo:payment},ip:input.ip});await c.query("COMMIT");return{status,paymentStatus:payment,shippingStatus:shipping}}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
